import Navbar from '@/app/Components/navbar'
import './globals.css'
import Footer from '@/app/Components/footer'
export const metadata = {
  title: 'Doculyz',
  description: 'Generated by Naimur Rahman',
  icons: {
    icon: '/favicon.png',
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
